---
- name: "Yt-dlp | {{ ansible_facts['distribution'] }} | Install yt-dlp"
  kewlfft.aur.aur:
    use: yay
    name:
      - yt-dlp
      - yt-dlp-ejs
    state: present
  become: yes
  become_user: aur_builder