---
- name: "Fastfetch | {{ ansible_facts['distribution'] }} | Install fastfetch"
  kewlfft.aur.aur:
    use: yay
    name:
      - fastfetch
    state: present
  become: yes
  become_user: aur_builder