---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "Gallery-dl | {{ ansible_facts['distribution'] }} | Ensure .config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/gallery-dl"
    state: directory
    mode: "0755"

- name: "Gallery-dl | {{ ansible_facts['distribution'] }} | Copy config file"
  ansible.builtin.copy:
    src: "{{ _files_path }}/config.json"
    dest: "{{ ansible_facts['user_dir'] }}/.config/gallery-dl/config.json"
    mode: "0644"